### ISSUE TITLE
Set-up Kanban - Board

### ISSUE THREAD

**Issue by Diegogagan2587** [Diegogagan2587/space-travelers#25]
# Implemented Changes

Set-up Kanban Board

- Link to the Project: https://github.com/Diegogagan2587/space-travelers
- Size of the Team: 2 Members

**Comment by joskalenda** [comment]
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @Team, |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
|  <img src="https://media0.giphy.com/media/l1KVaj5UcbHwrBMqI/giphy.gif"/> |

## Highlights

- [ ].. ✅ Project created
- [ ].. ✅ Tasks assigned up

## Required Changes ♻️

- [ ] We have a small issue that you will have to address before this Pull request is approved, in the requirement it is said that all the tasks for the 3 students are meant to be removed if the team only has 2, check these, [1](https://github.com/Diegogagan2587/space-travelers/issues/19),[2](https://github.com/Diegogagan2587/space-travelers/issues/16),[3](https://github.com/Diegogagan2587/space-travelers/issues/14),[4](https://github.com/Diegogagan2587/space-travelers/issues/11), [5](https://github.com/Diegogagan2587/space-travelers/issues/7), [8](https://github.com/Diegogagan2587/space-travelers/issues/4), [9](https://github.com/Diegogagan2587/space-travelers/issues/1) 

,
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by usorfaitheloho** [comment]
Hi @Diegogagan2587 and @joskalenda  , 
# STATUS: APPROVED! 🥇 💯 

![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
